#enviornment: test
environment: prod
server:
  # service type
  type: http
  # service port
  port: 8001
  # optional, port for web interface
  webPort: 8002
  # optional, internal port for web socket, replace this when it is conflict with your own service
  socketPort: 8003
  # the host of the service
  hostname: 127.0.0.1
  # the proxy rule
  rule: './rule.js'
  # optional, save request data to a specified file, will use in-memory db if not specified
  dbFile: null
  # optional, speed limit in kb/s
  throttle: 1024
  # optional, set it when you don't want to use the web interface
  disableWebInterface: false
  # set anyproxy as your system proxy
  setAsGlobalProxy: false
  # optional, do not print anything into terminal. do not set it when you are still debugging.
  silent: false
routes:
  '/':
    redirect:
      prod: passport.17shihui.com
      test: test.passport.17shihui.com
  '/passport':
    redirect:
      prod: passport.17shihui.com
      test: test.passport.17shihui.com
    auth: true
  'api/':
    redirect:
      prod: api.17shihui.com
      test: test.api.17shihui.com
    auth: false
  'passport/api':
    method: [GET,POST]
    redirect:
      prod: passport.api.17shihui.com
      test: test.passport.api.17shihui.com
    auth: true
  'no-redirect':
    auth: true
